-- Where each figure sits in BOT's own workbook.
--
-- A filed return is an .xlsx built by populating BOT's template, not a
-- spreadsheet of this system's own design. Which cell holds which figure is
-- therefore a fact about *their* file, and it is seeded here rather than
-- computed in code: when BOT inserts a line in a revision, the fix is a
-- migration, and the exporter is untouched.
--
-- The map is generated by `docs/reference/extract-bot-cells.py`, which reads
-- the template and resolves every taxonomy code against the seeds in migration
-- 0004. A name it cannot match fails at generation time.
--
-- One rule runs through the whole thing: **this system writes only where BOT's
-- template has no formula.** A cell BOT computes is BOT's answer, and writing
-- over it would replace their arithmetic with ours — the arithmetic their EDI
-- validator checks against. So computed cells simply have no row here and the
-- exporter has nowhere to put a figure for them.
--
-- The single exception is stated where it arises, below.

-- ---------------------------------------------------------------------------
-- The sheets
-- ---------------------------------------------------------------------------

CREATE TABLE reference.form_sheets (
  form_code       text     PRIMARY KEY,
  -- BOT's own tab name. Note MSP2-01's tab is spelled `MSP2_01` with an
  -- underscore and the other nine use a hyphen; that inconsistency is theirs.
  sheet_name      text     NOT NULL UNIQUE,
  -- A line's row is its Sno plus this. Uniform at 13 across all ten sheets
  -- today, held as a column so a revision that shifts one sheet's header does
  -- not shift the other nine.
  sno_row_offset  smallint NOT NULL CHECK (sno_row_offset > 0),
  -- The column carrying the institution's name (row 2), its MSP code (row 4)
  -- and the quarter-end date (row 6).
  --
  -- This is the exception to "never write where BOT has a formula". On nine of
  -- the ten sheets those three cells are `=[1]MSP2_01!C2` and the like: `[1]`
  -- is an external workbook named `minne.xlsm` that BOT does not ship with the
  -- template, and whose cached values read "TESTING MSP" / "M001" /
  -- 31-12-2021. Left alone, every form but the balance sheet would carry
  -- another institution's name. They are overwritten with literal values.
  identity_column text     NOT NULL CHECK (identity_column ~ '^[A-Z]{1,2}$')
);

COMMENT ON TABLE reference.form_sheets IS
  'One row per BOT MSP2 form: its sheet in the template, and how Sno maps to a row.';

-- ---------------------------------------------------------------------------
-- The columns
-- ---------------------------------------------------------------------------

-- Keyed by the name this system's own wire shapes use, so the exporter reads as
-- a translation between two vocabularies rather than a table of bare letters.
CREATE TABLE reference.form_columns (
  form_code     text NOT NULL REFERENCES reference.form_sheets (form_code),
  column_key    text NOT NULL,
  column_letter text NOT NULL CHECK (column_letter ~ '^[A-Z]{1,2}$'),
  PRIMARY KEY (form_code, column_key),
  -- Two figures in one cell would mean one of them is lost, and which one
  -- would depend on write order.
  UNIQUE (form_code, column_letter)
);

-- ---------------------------------------------------------------------------
-- The rows
-- ---------------------------------------------------------------------------

-- What a row is *about* differs by form: a numbered line on the balance sheet,
-- a sector on MSP2-03, a district on MSP2-10. Each is a real foreign key rather
-- than a free-text discriminator, so a map row that names something the
-- reference data does not contain cannot be inserted at all.
CREATE TABLE reference.form_rows (
  form_code      text     NOT NULL REFERENCES reference.form_sheets (form_code),
  row_number     smallint NOT NULL CHECK (row_number >= 14),
  sno            smallint,
  sector_code    text     REFERENCES reference.sectors (code),
  loan_type_code text     REFERENCES reference.loan_types (code),
  district_code  text     REFERENCES reference.districts (code),
  PRIMARY KEY (form_code, row_number),
  -- A row addresses exactly one thing. Two would make the exporter's lookup
  -- ambiguous; none would make the row unreachable.
  CONSTRAINT form_rows_addresses_one_thing CHECK (
    (sno IS NOT NULL)::int
      + (sector_code IS NOT NULL)::int
      + (loan_type_code IS NOT NULL)::int
      + (district_code IS NOT NULL)::int = 1
  ),
  -- A numbered line must be a line BOT actually has. `reference.form_lines` is
  -- seeded for the three forms addressed that way.
  CONSTRAINT form_rows_line_exists
    FOREIGN KEY (form_code, sno) REFERENCES reference.form_lines (form_code, sno)
);

-- The same subject cannot appear on two rows of one form, in either direction.
CREATE UNIQUE INDEX form_rows_sector_idx
  ON reference.form_rows (form_code, sector_code) WHERE sector_code IS NOT NULL;
CREATE UNIQUE INDEX form_rows_loan_type_idx
  ON reference.form_rows (form_code, loan_type_code) WHERE loan_type_code IS NOT NULL;
CREATE UNIQUE INDEX form_rows_district_idx
  ON reference.form_rows (form_code, district_code) WHERE district_code IS NOT NULL;

-- ---------------------------------------------------------------------------
-- The free sections
-- ---------------------------------------------------------------------------

-- MSP2-07 and MSP2-08 do not name their counterparties in advance: the rows are
-- blank, and the institution picks a bank from a dropdown beside the amount. So
-- those forms are addressed as ranges filled in order, and the number of rows
-- BOT allows is a real limit — an institution banking with twenty-nine banks
-- has one it cannot report. The exporter refuses rather than dropping a
-- holding, because a return that is quietly short is worse than one that is
-- late.
CREATE TABLE reference.form_sections (
  form_code   text     NOT NULL REFERENCES reference.form_sheets (form_code),
  section_key text     NOT NULL,
  first_row   smallint NOT NULL CHECK (first_row >= 14),
  last_row    smallint NOT NULL,
  PRIMARY KEY (form_code, section_key),
  CONSTRAINT form_sections_is_a_range CHECK (last_row >= first_row)
);

-- ---------------------------------------------------------------------------
-- The map
-- ---------------------------------------------------------------------------

INSERT INTO reference.form_sheets
  (form_code, sheet_name, sno_row_offset, identity_column) VALUES
  ('MSP2-01', 'MSP2_01', 13, 'C'),
  ('MSP2-02', 'MSP2-02', 13, 'C'),
  ('MSP2-03', 'MSP2-03', 13, 'D'),
  ('MSP2-04', 'MSP2-04', 13, 'D'),
  ('MSP2-05', 'MSP2-05', 13, 'D'),
  ('MSP2-07', 'MSP2-07', 13, 'F'),
  ('MSP2-08', 'MSP2-08', 13, 'E'),
  ('MSP2-09', 'MSP2-09', 13, 'D'),
  ('MSP2-10', 'MSP2-10', 13, 'H');

INSERT INTO reference.form_columns (form_code, column_key, column_letter) VALUES
  ('MSP2-01', 'amount', 'C'),
  ('MSP2-02', 'quarter_amount', 'C'),
  ('MSP2-02', 'year_to_date_amount', 'D'),
  ('MSP2-03', 'borrower_count', 'C'),
  ('MSP2-03', 'current', 'E'),
  ('MSP2-03', 'esm', 'F'),
  ('MSP2-03', 'substandard', 'G'),
  ('MSP2-03', 'doubtful', 'H'),
  ('MSP2-03', 'loss', 'I'),
  ('MSP2-03', 'written_off_during_period', 'J'),
  ('MSP2-04', 'borrower_count', 'C'),
  ('MSP2-04', 'total_outstanding', 'D'),
  ('MSP2-04', 'straight_line_lowest', 'F'),
  ('MSP2-04', 'straight_line_highest', 'G'),
  ('MSP2-04', 'reducing_balance_lowest', 'I'),
  ('MSP2-04', 'reducing_balance_highest', 'J'),
  ('MSP2-05', 'amount', 'C'),
  ('MSP2-07', 'counterparty', 'B'),
  ('MSP2-07', 'deposit_tzs', 'C'),
  ('MSP2-07', 'deposit_foreign_tzs_equivalent', 'D'),
  ('MSP2-07', 'borrowing_tzs', 'F'),
  ('MSP2-07', 'borrowing_foreign_tzs_equivalent', 'G'),
  ('MSP2-08', 'counterparty', 'B'),
  ('MSP2-08', 'balance', 'C'),
  ('MSP2-09', 'female_count', 'C'),
  ('MSP2-09', 'female_amount', 'D'),
  ('MSP2-09', 'male_count', 'E'),
  ('MSP2-09', 'male_amount', 'F'),
  ('MSP2-10', 'branch_count', 'C'),
  ('MSP2-10', 'employee_count', 'D'),
  ('MSP2-10', 'compulsory_savings', 'E'),
  ('MSP2-10', 'borrowers_up_to_35_female', 'F'),
  ('MSP2-10', 'borrowers_up_to_35_male', 'G'),
  ('MSP2-10', 'borrowers_above_35_female', 'H'),
  ('MSP2-10', 'borrowers_above_35_male', 'I'),
  ('MSP2-10', 'loans_up_to_35_female', 'J'),
  ('MSP2-10', 'loans_up_to_35_male', 'K'),
  ('MSP2-10', 'loans_above_35_female', 'L'),
  ('MSP2-10', 'loans_above_35_male', 'M'),
  ('MSP2-10', 'outstanding_up_to_35_female', 'N'),
  ('MSP2-10', 'outstanding_up_to_35_male', 'O'),
  ('MSP2-10', 'outstanding_above_35_female', 'P'),
  ('MSP2-10', 'outstanding_above_35_male', 'Q');

INSERT INTO reference.form_sections
  (form_code, section_key, first_row, last_row) VALUES
  ('MSP2-07', 'bank_tanzania', 15, 42),
  ('MSP2-07', 'microfinance_service_provider', 45, 58),
  ('MSP2-07', 'mno', 61, 68),
  ('MSP2-07', 'bank_abroad', 72, 77),
  ('MSP2-08', 'agent_banking', 15, 42);

INSERT INTO reference.form_rows (form_code, row_number, sno) VALUES
  ('MSP2-01', 15, 2),
  ('MSP2-01', 17, 4),
  ('MSP2-01', 18, 5),
  ('MSP2-01', 19, 6),
  ('MSP2-01', 20, 7),
  ('MSP2-01', 22, 9),
  ('MSP2-01', 23, 10),
  ('MSP2-01', 24, 11),
  ('MSP2-01', 25, 12),
  ('MSP2-01', 26, 13),
  ('MSP2-01', 28, 15),
  ('MSP2-01', 29, 16),
  ('MSP2-01', 31, 18),
  ('MSP2-01', 32, 19),
  ('MSP2-01', 33, 20),
  ('MSP2-01', 34, 21),
  ('MSP2-01', 35, 22),
  ('MSP2-01', 37, 24),
  ('MSP2-01', 38, 25),
  ('MSP2-01', 40, 27),
  ('MSP2-01', 41, 28),
  ('MSP2-01', 42, 29),
  ('MSP2-01', 43, 30),
  ('MSP2-01', 44, 31),
  ('MSP2-01', 45, 32),
  ('MSP2-01', 47, 34),
  ('MSP2-01', 50, 37),
  ('MSP2-01', 51, 38),
  ('MSP2-01', 52, 39),
  ('MSP2-01', 53, 40),
  ('MSP2-01', 54, 41),
  ('MSP2-01', 56, 43),
  ('MSP2-01', 57, 44),
  ('MSP2-01', 58, 45),
  ('MSP2-01', 59, 46),
  ('MSP2-01', 60, 47),
  ('MSP2-01', 61, 48),
  ('MSP2-01', 62, 49),
  ('MSP2-01', 65, 52),
  ('MSP2-01', 66, 53),
  ('MSP2-01', 67, 54),
  ('MSP2-01', 68, 55),
  ('MSP2-01', 69, 56),
  ('MSP2-01', 70, 57),
  ('MSP2-01', 71, 58),
  ('MSP2-01', 72, 59),
  ('MSP2-01', 73, 60),
  ('MSP2-02', 15, 2),
  ('MSP2-02', 16, 3),
  ('MSP2-02', 17, 4),
  ('MSP2-02', 18, 5),
  ('MSP2-02', 19, 6),
  ('MSP2-02', 21, 8),
  ('MSP2-02', 22, 9),
  ('MSP2-02', 23, 10),
  ('MSP2-02', 24, 11),
  ('MSP2-02', 25, 12),
  ('MSP2-02', 27, 14),
  ('MSP2-02', 28, 15),
  ('MSP2-02', 30, 17),
  ('MSP2-02', 31, 18),
  ('MSP2-02', 32, 19),
  ('MSP2-02', 33, 20),
  ('MSP2-02', 34, 21),
  ('MSP2-02', 35, 22),
  ('MSP2-02', 37, 24),
  ('MSP2-02', 38, 25),
  ('MSP2-02', 39, 26),
  ('MSP2-02', 40, 27),
  ('MSP2-02', 41, 28),
  ('MSP2-02', 42, 29),
  ('MSP2-02', 43, 30),
  ('MSP2-02', 44, 31),
  ('MSP2-02', 45, 32),
  ('MSP2-02', 46, 33),
  ('MSP2-02', 47, 34),
  ('MSP2-02', 48, 35),
  ('MSP2-02', 49, 36),
  ('MSP2-02', 50, 37),
  ('MSP2-02', 51, 38),
  ('MSP2-02', 52, 39),
  ('MSP2-02', 54, 41),
  ('MSP2-05', 15, 2),
  ('MSP2-05', 16, 3),
  ('MSP2-05', 17, 4),
  ('MSP2-05', 18, 5),
  ('MSP2-05', 19, 6),
  ('MSP2-05', 20, 7),
  ('MSP2-05', 21, 8),
  ('MSP2-05', 22, 9),
  ('MSP2-05', 23, 10);

INSERT INTO reference.form_rows (form_code, row_number, sector_code) VALUES
  ('MSP2-03', 14, 'agriculture'),
  ('MSP2-03', 17, 'fishing'),
  ('MSP2-03', 20, 'forest'),
  ('MSP2-03', 23, 'hunting'),
  ('MSP2-03', 26, 'financial_intermediaries'),
  ('MSP2-03', 29, 'mining_and_quarrying'),
  ('MSP2-03', 32, 'manufacturing'),
  ('MSP2-03', 35, 'building_and_construction'),
  ('MSP2-03', 38, 'real_estate'),
  ('MSP2-03', 41, 'leasing'),
  ('MSP2-03', 44, 'transport_and_communication'),
  ('MSP2-03', 47, 'trade'),
  ('MSP2-03', 50, 'tourism'),
  ('MSP2-03', 53, 'hotels_and_restaurants'),
  ('MSP2-03', 56, 'warehousing_and_storage'),
  ('MSP2-03', 59, 'electricity'),
  ('MSP2-03', 62, 'gas'),
  ('MSP2-03', 65, 'water'),
  ('MSP2-03', 68, 'education'),
  ('MSP2-03', 71, 'health'),
  ('MSP2-03', 74, 'other_services'),
  ('MSP2-03', 77, 'personal_private'),
  ('MSP2-09', 14, 'agriculture'),
  ('MSP2-09', 17, 'fishing'),
  ('MSP2-09', 20, 'forest'),
  ('MSP2-09', 23, 'hunting'),
  ('MSP2-09', 26, 'financial_intermediaries'),
  ('MSP2-09', 29, 'mining_and_quarrying'),
  ('MSP2-09', 32, 'manufacturing'),
  ('MSP2-09', 35, 'building_and_construction'),
  ('MSP2-09', 38, 'real_estate'),
  ('MSP2-09', 41, 'leasing'),
  ('MSP2-09', 44, 'transport_and_communication'),
  ('MSP2-09', 47, 'trade'),
  ('MSP2-09', 50, 'tourism'),
  ('MSP2-09', 53, 'hotels_and_restaurants'),
  ('MSP2-09', 56, 'warehousing_and_storage'),
  ('MSP2-09', 59, 'electricity'),
  ('MSP2-09', 62, 'gas'),
  ('MSP2-09', 65, 'water'),
  ('MSP2-09', 68, 'education'),
  ('MSP2-09', 71, 'health'),
  ('MSP2-09', 74, 'other_services'),
  ('MSP2-09', 77, 'personal_private');

INSERT INTO reference.form_rows (form_code, row_number, loan_type_code) VALUES
  ('MSP2-04', 14, 'business_group_loans'),
  ('MSP2-04', 15, 'business_solidarity_small_group_loans'),
  ('MSP2-04', 16, 'business_individual_loans'),
  ('MSP2-04', 17, 'agriculture_loans'),
  ('MSP2-04', 18, 'housing_microfinance_loans'),
  ('MSP2-04', 19, 'microleasing_hire_purchase_loans'),
  ('MSP2-04', 20, 'loans_to_other_microfinance_service_providers_e_g_saccos'),
  ('MSP2-04', 21, 'micro_insurance_loans'),
  ('MSP2-04', 22, 'education_loan'),
  ('MSP2-04', 23, 'salaried_loans'),
  ('MSP2-04', 24, 'government_employees'),
  ('MSP2-04', 25, 'non_government_employees'),
  ('MSP2-04', 26, 'emergence_loans'),
  ('MSP2-04', 27, 'other_micro_loans');

INSERT INTO reference.form_rows (form_code, row_number, district_code) VALUES
  ('MSP2-10', 16, 'tz_arusha__arusha_cc'),
  ('MSP2-10', 17, 'tz_arusha__arusha_dc'),
  ('MSP2-10', 18, 'tz_arusha__karatu'),
  ('MSP2-10', 19, 'tz_arusha__longido_dc'),
  ('MSP2-10', 20, 'tz_arusha__meru'),
  ('MSP2-10', 21, 'tz_arusha__monduli'),
  ('MSP2-10', 22, 'tz_arusha__ngorongoro'),
  ('MSP2-10', 24, 'tz_dar_es_salaam__ilala_mc'),
  ('MSP2-10', 25, 'tz_dar_es_salaam__kigamboni_mc'),
  ('MSP2-10', 26, 'tz_dar_es_salaam__kinondoni_mc'),
  ('MSP2-10', 27, 'tz_dar_es_salaam__temeke_mc'),
  ('MSP2-10', 28, 'tz_dar_es_salaam__ubungo_mc'),
  ('MSP2-10', 30, 'tz_dodoma__bahi_dc'),
  ('MSP2-10', 31, 'tz_dodoma__chamwino_dc'),
  ('MSP2-10', 32, 'tz_dodoma__chemba_dc'),
  ('MSP2-10', 33, 'tz_dodoma__dodoma_cc'),
  ('MSP2-10', 34, 'tz_dodoma__kondoa_dc'),
  ('MSP2-10', 35, 'tz_dodoma__kondoa_tc'),
  ('MSP2-10', 36, 'tz_dodoma__kongwa_dc'),
  ('MSP2-10', 37, 'tz_dodoma__mpwapwa_dc'),
  ('MSP2-10', 39, 'tz_geita__bukombe'),
  ('MSP2-10', 40, 'tz_geita__chato_dc'),
  ('MSP2-10', 41, 'tz_geita__geita_dc'),
  ('MSP2-10', 42, 'tz_geita__geita_tc'),
  ('MSP2-10', 43, 'tz_geita__mbogwe_dc'),
  ('MSP2-10', 45, 'tz_iringa__iringa_dc'),
  ('MSP2-10', 46, 'tz_iringa__iringa_mc'),
  ('MSP2-10', 47, 'tz_iringa__kilolo_dc'),
  ('MSP2-10', 48, 'tz_iringa__mafinga_tc'),
  ('MSP2-10', 49, 'tz_iringa__mufindi_dc'),
  ('MSP2-10', 51, 'tz_kagera__biharamulo_dc'),
  ('MSP2-10', 52, 'tz_kagera__bukoba_dc'),
  ('MSP2-10', 53, 'tz_kagera__bukoba_mc'),
  ('MSP2-10', 54, 'tz_kagera__karagwe_dc'),
  ('MSP2-10', 55, 'tz_kagera__kyerwa_dc'),
  ('MSP2-10', 56, 'tz_kagera__missenyi_dc'),
  ('MSP2-10', 57, 'tz_kagera__muleba_dc'),
  ('MSP2-10', 58, 'tz_kagera__ngara_dc'),
  ('MSP2-10', 60, 'tz_katavi__mlele_dc'),
  ('MSP2-10', 61, 'tz_katavi__mpanda_dc'),
  ('MSP2-10', 62, 'tz_katavi__mpanda_mc'),
  ('MSP2-10', 63, 'tz_katavi__mpimbwe_dc'),
  ('MSP2-10', 64, 'tz_katavi__nsimbo_dc'),
  ('MSP2-10', 66, 'tz_kigoma__buhigwe_dc'),
  ('MSP2-10', 67, 'tz_kigoma__kakonko_dc'),
  ('MSP2-10', 68, 'tz_kigoma__kasulu_dc'),
  ('MSP2-10', 69, 'tz_kigoma__kasulu_tc'),
  ('MSP2-10', 70, 'tz_kigoma__kibondo_dc'),
  ('MSP2-10', 71, 'tz_kigoma__kigoma_dc'),
  ('MSP2-10', 72, 'tz_kigoma__kigoma_mc'),
  ('MSP2-10', 73, 'tz_kigoma__uvinza_dc'),
  ('MSP2-10', 75, 'tz_kilimanjaro__hai_dc'),
  ('MSP2-10', 76, 'tz_kilimanjaro__moshi_dc'),
  ('MSP2-10', 77, 'tz_kilimanjaro__moshi_mc'),
  ('MSP2-10', 78, 'tz_kilimanjaro__mwanga_dc'),
  ('MSP2-10', 79, 'tz_kilimanjaro__rombo_dc'),
  ('MSP2-10', 80, 'tz_kilimanjaro__same_dc'),
  ('MSP2-10', 81, 'tz_kilimanjaro__siha_dc'),
  ('MSP2-10', 83, 'tz_lindi__kilwa_dc'),
  ('MSP2-10', 84, 'tz_lindi__lindi_dc'),
  ('MSP2-10', 85, 'tz_lindi__lindi_mc'),
  ('MSP2-10', 86, 'tz_lindi__liwale_dc'),
  ('MSP2-10', 87, 'tz_lindi__nachingwea_dc'),
  ('MSP2-10', 88, 'tz_lindi__ruangwa_dc'),
  ('MSP2-10', 90, 'tz_manyara__babati_dc'),
  ('MSP2-10', 91, 'tz_manyara__babati_tc'),
  ('MSP2-10', 92, 'tz_manyara__hanang_dc'),
  ('MSP2-10', 93, 'tz_manyara__kiteto_dc'),
  ('MSP2-10', 94, 'tz_manyara__mbulu_dc'),
  ('MSP2-10', 95, 'tz_manyara__mbulu_tc'),
  ('MSP2-10', 96, 'tz_manyara__simanjiro_dc'),
  ('MSP2-10', 98, 'tz_mara__bunda_dc'),
  ('MSP2-10', 99, 'tz_mara__bunda_tc'),
  ('MSP2-10', 100, 'tz_mara__butiama_dc'),
  ('MSP2-10', 101, 'tz_mara__musoma_dc'),
  ('MSP2-10', 102, 'tz_mara__musoma_mc'),
  ('MSP2-10', 103, 'tz_mara__rorya_dc'),
  ('MSP2-10', 104, 'tz_mara__serengeti_dc'),
  ('MSP2-10', 105, 'tz_mara__tarime_dc'),
  ('MSP2-10', 106, 'tz_mara__tarime_tc'),
  ('MSP2-10', 108, 'tz_mbeya__busokelo_dc'),
  ('MSP2-10', 109, 'tz_mbeya__chunya_dc'),
  ('MSP2-10', 110, 'tz_mbeya__kyela_dc'),
  ('MSP2-10', 111, 'tz_mbeya__mbarali_dc'),
  ('MSP2-10', 112, 'tz_mbeya__mbeya_cc'),
  ('MSP2-10', 113, 'tz_mbeya__mbeya_dc'),
  ('MSP2-10', 114, 'tz_mbeya__rungwe_dc'),
  ('MSP2-10', 116, 'tz_morogoro__gairo_dc'),
  ('MSP2-10', 117, 'tz_morogoro__ifakara_tc'),
  ('MSP2-10', 118, 'tz_morogoro__kilombero_dc'),
  ('MSP2-10', 119, 'tz_morogoro__kilosa_dc'),
  ('MSP2-10', 120, 'tz_morogoro__morogoro_dc'),
  ('MSP2-10', 121, 'tz_morogoro__morogoro_mc'),
  ('MSP2-10', 122, 'tz_morogoro__mvomero_dc'),
  ('MSP2-10', 123, 'tz_morogoro__ulanga_dc'),
  ('MSP2-10', 125, 'tz_mtwara__masasi_dc'),
  ('MSP2-10', 126, 'tz_mtwara__masasi_tc'),
  ('MSP2-10', 127, 'tz_mtwara__mtwara_dc'),
  ('MSP2-10', 128, 'tz_mtwara__mtwara_mc'),
  ('MSP2-10', 129, 'tz_mtwara__nanyamba_tc'),
  ('MSP2-10', 130, 'tz_mtwara__nanyumbu_dc'),
  ('MSP2-10', 131, 'tz_mtwara__newala_dc'),
  ('MSP2-10', 132, 'tz_mtwara__newala_tc'),
  ('MSP2-10', 133, 'tz_mtwara__tandahimba_dc'),
  ('MSP2-10', 135, 'tz_mwanza__buchosa_dc'),
  ('MSP2-10', 136, 'tz_mwanza__ilemela_mc'),
  ('MSP2-10', 137, 'tz_mwanza__kwimba_dc'),
  ('MSP2-10', 138, 'tz_mwanza__magu_dc'),
  ('MSP2-10', 139, 'tz_mwanza__misungwi_dc'),
  ('MSP2-10', 140, 'tz_mwanza__sengerema_dc'),
  ('MSP2-10', 141, 'tz_mwanza__ukerewe_dc'),
  ('MSP2-10', 143, 'tz_njombe__ludewa_dc'),
  ('MSP2-10', 144, 'tz_njombe__makambako_tc'),
  ('MSP2-10', 145, 'tz_njombe__makete_dc'),
  ('MSP2-10', 146, 'tz_njombe__njombe_dc'),
  ('MSP2-10', 147, 'tz_njombe__njombe_tc'),
  ('MSP2-10', 148, 'tz_njombe__wanging_ombe_dc'),
  ('MSP2-10', 150, 'tz_pwani__bagamoyo_dc'),
  ('MSP2-10', 151, 'tz_pwani__chalinze_dc'),
  ('MSP2-10', 152, 'tz_pwani__kibaha_dc'),
  ('MSP2-10', 153, 'tz_pwani__kibaha_tc'),
  ('MSP2-10', 154, 'tz_pwani__kibiti_dc'),
  ('MSP2-10', 155, 'tz_pwani__kisarawe_dc'),
  ('MSP2-10', 156, 'tz_pwani__mafia_dc'),
  ('MSP2-10', 157, 'tz_pwani__mkuranga_dc'),
  ('MSP2-10', 158, 'tz_pwani__rufiji_dc'),
  ('MSP2-10', 160, 'tz_rukwa__kalambo_dc'),
  ('MSP2-10', 161, 'tz_rukwa__nkasi_dc'),
  ('MSP2-10', 162, 'tz_rukwa__sumbawanga_dc'),
  ('MSP2-10', 163, 'tz_rukwa__sumbawanga_mc'),
  ('MSP2-10', 165, 'tz_ruvuma__madaba_dc'),
  ('MSP2-10', 166, 'tz_ruvuma__mbinga_dc'),
  ('MSP2-10', 167, 'tz_ruvuma__mbinga_tc'),
  ('MSP2-10', 168, 'tz_ruvuma__namtumbo_dc'),
  ('MSP2-10', 169, 'tz_ruvuma__nyasa_dc'),
  ('MSP2-10', 170, 'tz_ruvuma__songea_dc'),
  ('MSP2-10', 171, 'tz_ruvuma__songea_mc'),
  ('MSP2-10', 172, 'tz_ruvuma__tunduru_dc'),
  ('MSP2-10', 174, 'tz_shinyanga__kahama_tc'),
  ('MSP2-10', 175, 'tz_shinyanga__kishapu_dc'),
  ('MSP2-10', 176, 'tz_shinyanga__msalala_dc'),
  ('MSP2-10', 177, 'tz_shinyanga__shinyanga_dc'),
  ('MSP2-10', 178, 'tz_shinyanga__shinyanga_mc'),
  ('MSP2-10', 179, 'tz_shinyanga__ushetu_dc'),
  ('MSP2-10', 181, 'tz_simiyu__bariadi_dc'),
  ('MSP2-10', 182, 'tz_simiyu__bariadi_tc'),
  ('MSP2-10', 183, 'tz_simiyu__busega_dc'),
  ('MSP2-10', 184, 'tz_simiyu__itilima_dc'),
  ('MSP2-10', 185, 'tz_simiyu__maswa_dc'),
  ('MSP2-10', 186, 'tz_simiyu__meatu_dc'),
  ('MSP2-10', 188, 'tz_singida__ikungi_dc'),
  ('MSP2-10', 189, 'tz_singida__iramba_dc'),
  ('MSP2-10', 190, 'tz_singida__itigi_dc'),
  ('MSP2-10', 191, 'tz_singida__manyoni_dc'),
  ('MSP2-10', 192, 'tz_singida__mkalama_dc'),
  ('MSP2-10', 193, 'tz_singida__singida_dc'),
  ('MSP2-10', 194, 'tz_singida__singida_mc'),
  ('MSP2-10', 196, 'tz_songwe__ileje_dc'),
  ('MSP2-10', 197, 'tz_songwe__mbozi_dc'),
  ('MSP2-10', 198, 'tz_songwe__momba_dc'),
  ('MSP2-10', 199, 'tz_songwe__songwe_dc'),
  ('MSP2-10', 200, 'tz_songwe__tunduma_tc'),
  ('MSP2-10', 202, 'tz_tabora__igunga_dc'),
  ('MSP2-10', 203, 'tz_tabora__kaliua_dc'),
  ('MSP2-10', 204, 'tz_tabora__nzega_dc'),
  ('MSP2-10', 205, 'tz_tabora__nzega_tc'),
  ('MSP2-10', 206, 'tz_tabora__sikonge_dc'),
  ('MSP2-10', 207, 'tz_tabora__tabora_dc'),
  ('MSP2-10', 208, 'tz_tabora__tabora_mc'),
  ('MSP2-10', 209, 'tz_tabora__urambo_dc'),
  ('MSP2-10', 211, 'tz_tanga__bumbuli_dc'),
  ('MSP2-10', 212, 'tz_tanga__handeni_dc'),
  ('MSP2-10', 213, 'tz_tanga__handeni_tc'),
  ('MSP2-10', 214, 'tz_tanga__kilindi_dc'),
  ('MSP2-10', 215, 'tz_tanga__korogwe_dc'),
  ('MSP2-10', 216, 'tz_tanga__korogwe_tc'),
  ('MSP2-10', 217, 'tz_tanga__lushoto_dc'),
  ('MSP2-10', 218, 'tz_tanga__mbulu_dc'),
  ('MSP2-10', 219, 'tz_tanga__mkinga_dc'),
  ('MSP2-10', 220, 'tz_tanga__muheza_dc'),
  ('MSP2-10', 221, 'tz_tanga__pangani_dc'),
  ('MSP2-10', 222, 'tz_tanga__tanga_cc'),
  ('MSP2-10', 226, 'zn_kusini_pemba__chakechake'),
  ('MSP2-10', 227, 'zn_kusini_pemba__mkoani'),
  ('MSP2-10', 229, 'zn_kaskazini_pemba__micheweni'),
  ('MSP2-10', 230, 'zn_kaskazini_pemba__wete'),
  ('MSP2-10', 232, 'zn_mjini_magharibi_unguja__magharibi_a'),
  ('MSP2-10', 233, 'zn_mjini_magharibi_unguja__magharibi_b'),
  ('MSP2-10', 234, 'zn_mjini_magharibi_unguja__mjini'),
  ('MSP2-10', 236, 'zn_kaskazini_unguja__kaskazini_a'),
  ('MSP2-10', 237, 'zn_kaskazini_unguja__kaskazini_b'),
  ('MSP2-10', 239, 'zn_kusini_unguja__kati'),
  ('MSP2-10', 240, 'zn_kusini_unguja__kusini');
-- 91 numbered lines, 44 sector rows, 14 loan-type rows, 193 district rows.

-- Sno34 has a writable cell and no formula, and is still not a cell this system
-- may fill. Migration 0015 established why: "8. LIABILITIES" is a section
-- heading, and Sno50 (Total Liabilities) sums Sno35, 46, 47, 48 and 49 without
-- it. A figure written there is reported nowhere. Entry is already refused; the
-- exporter is given no cell to write either, so the two agree.
DELETE FROM reference.form_rows WHERE form_code = 'MSP2-01' AND sno = 34;

-- ---------------------------------------------------------------------------
-- Access
-- ---------------------------------------------------------------------------

-- Reference data, like the rest of the schema: readable by the application
-- role, written only by a migration.
GRANT SELECT ON reference.form_sheets, reference.form_columns,
                reference.form_rows, reference.form_sections TO mfi_app;
