import { type LoanRestructuring, type RestructureLoanRequest } from '@mfi/contracts';
import { endOfMonth, generateSchedule, quoteSettlement } from '@mfi/domain';
import { canActOnBranch, type Principal } from '@mfi/identity';
import { Money, Rate } from '@mfi/money';

import { conflict, notFound, ruleViolation } from '../../http/errors.js';
import {
  type RestructuringRepository,
  type RestructuringSubject,
} from './restructuring-repository.js';

/**
 * Restructuring a loan into a successor.
 *
 * The new principal is what the borrower would have had to pay to clear the old
 * loan on the day of the restructuring — remaining principal, unpaid accrued
 * interest, and every outstanding penalty. That is exactly the settlement
 * quote, so it is computed by `quoteSettlement` rather than by a second
 * implementation of the same arithmetic.
 *
 * Reusing it is not a shortcut. Settlement and restructuring ask the same
 * question — "what does this loan still owe today?" — and answering it twice in
 * two places is how the two come to disagree by a shilling on a borrower who
 * asks for both figures in the same conversation.
 */

function formatDateOnly(value: Date): string {
  const year = String(value.getFullYear()).padStart(4, '0');
  const month = String(value.getMonth() + 1).padStart(2, '0');
  const day = String(value.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

/** What the old loan owes, and what the successor's principal will be. */
function carriedBalances(
  subject: RestructuringSubject,
  effectiveOn: string,
): {
  principalCarried: Money;
  interestCapitalised: Money;
  penaltiesCapitalised: Money;
  newPrincipal: Money;
} {
  const quote = quoteSettlement({
    settlementDate: effectiveOn,
    outstandingPrincipal: Money.fromDatabaseValue(subject.outstandingPrincipal),
    penaltyOutstanding: Money.fromDatabaseValue(subject.penaltyOutstanding),
    schedule: subject.schedule.map((instalment) => ({
      dueDate: instalment.dueDate,
      interestDue: Money.fromDatabaseValue(instalment.interestDue),
    })),
    interestAlreadyPaid: Money.fromDatabaseValue(subject.interestAlreadyPaid),
  });

  return {
    principalCarried: quote.principal,
    interestCapitalised: quote.interest,
    penaltiesCapitalised: quote.penalty,
    newPrincipal: quote.total,
  };
}

/**
 * Restructure the loan.
 *
 * Eligibility is the rule with the sharpest edge: the request is permitted only
 * while the loan is **still within its originally agreed term**. Past the
 * original maturity month this route is unavailable, and a loan in that state
 * needs a different conversation — not an automatic rescheduling of a facility
 * that has already run its course.
 *
 * The comparison is by month, matching how settlement charges interest, so a
 * loan maturing in October can be restructured on any day of October and on no
 * day of November.
 */
export async function restructureLoan(
  principal: Principal,
  loanId: string,
  request: RestructureLoanRequest,
  repository: RestructuringRepository,
  now: () => Date,
): Promise<LoanRestructuring> {
  const subject = await repository.subject(principal.institutionId, principal.userId, loanId);

  if (subject === null || !canActOnBranch(principal, subject.branchId)) {
    throw notFound('No such loan.');
  }

  if (subject.alreadyRestructured) {
    throw conflict('That loan has already been restructured.');
  }

  if (subject.status !== 'active') {
    throw ruleViolation(`Only an active loan can be restructured; this one is ${subject.status}.`);
  }

  const today = formatDateOnly(now());
  const effectiveOn = request.effectiveOn ?? today;

  if (effectiveOn > today) {
    throw ruleViolation('A restructuring cannot be dated in the future.');
  }

  if (subject.originalMaturity === null) {
    throw ruleViolation('That loan has no repayment schedule, so it has no agreed term.');
  }

  if (endOfMonth(effectiveOn) > endOfMonth(subject.originalMaturity)) {
    throw ruleViolation(
      `That loan's agreed term ended in ${subject.originalMaturity.slice(0, 7)}. ` +
        'Restructuring is only available while a loan is still within its original term.',
    );
  }

  const carried = carriedBalances(subject, effectiveOn);

  if (!carried.newPrincipal.isPositive()) {
    // Nothing owed is nothing to restructure. It would also violate the
    // positive-principal constraint on the successor.
    throw ruleViolation('That loan owes nothing, so there is nothing to restructure.');
  }

  // The successor's schedule, on the new principal — which includes the
  // capitalised interest and penalties, so interest is charged on all of it.
  // Generated by the same `generateSchedule` an ordinary advance uses; there is
  // no second implementation to drift from.
  const schedule = generateSchedule({
    principal: carried.newPrincipal,
    monthlyRate: Rate.ofMonthlyFraction(subject.monthlyRate),
    termMonths: subject.termMonths,
    method: subject.interestMethod,
    disbursementDate: new Date(`${effectiveOn}T00:00:00Z`),
  });

  const recorded = await repository.restructure(principal.institutionId, principal.userId, {
    oldLoanId: loanId,
    principalCarried: carried.principalCarried.toDatabaseValue(),
    interestCapitalised: carried.interestCapitalised.toDatabaseValue(),
    penaltiesCapitalised: carried.penaltiesCapitalised.toDatabaseValue(),
    newPrincipal: carried.newPrincipal.toDatabaseValue(),
    reason: request.reason,
    requestedBy: principal.userId,
    effectiveOn,
    schedule,
  });

  if (recorded === null) {
    // The closing UPDATE is conditional on the loan still being active, so a
    // second or concurrent request stops before writing anything else.
    throw conflict('That loan changed while the restructuring was being recorded.');
  }

  return recorded;
}

/**
 * The restructuring a loan was part of, from either side.
 *
 * Its own reader because `loan_restructurings` was otherwise a table the
 * application wrote and never read — the same shape of defect this project has
 * already repaired twice, in `audit_logs` and in `invitations`. The link on the
 * loan tells you *that* it happened; this says what was carried across.
 */
export async function getRestructuring(
  principal: Principal,
  loanId: string,
  repository: RestructuringRepository,
): Promise<LoanRestructuring> {
  const subject = await repository.subject(principal.institutionId, principal.userId, loanId);

  if (subject === null || !canActOnBranch(principal, subject.branchId)) {
    throw notFound('No such loan.');
  }

  const found = await repository.findFor(principal.institutionId, principal.userId, loanId);

  if (found === null) {
    throw notFound('That loan has not been restructured.');
  }

  return found;
}
